VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IWorksheetChangeCategoriser"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "src.categorisers"
Option Explicit

Public Sub CategoriseChange( _
       ByVal events As ITableEventsSource, _
       ByVal target As Range, _
       ByVal table As ListObject _
       )
End Sub
